---
pagetitle: "Sievert Consulting - R, RStudio, shiny, plotly, data visualization consulting, training, instruction"
output:
  html_document:
    highlight: null
    mathjax: null
    toc_float: false
    self_contained: false
    css: ['css/index.css', 'css/font-awesome.min.css']
    includes:
      in_header: header.html
---

<!--html_preserve-->

<!--
https://getbootstrap.com/components/#navbar
-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
  
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-list" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SIEVERT CONSULTING</a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-list">
      <ul class="nav navbar-nav navbar-right"> 
        <li><a href="#Services">Services</a></li>
        <li><a href="#Training">Training</a></li>
        <li><a href="#About">About</a></li>
        <li><a href="#Contact">Contact</a></li>
      </ul>
    </div>

  </div>
</nav>
<!--/html_preserve-->

```{r, include = FALSE}
library("htmltools")
library("bsplus")
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE
)
```


```{r main}
# carousel for initial section
welcome_carousel <- bs_carousel(id = "carousel-o-graphics") %>%
  bs_set_data(interval = FALSE) %>%
  bs_append(
    content = bs_carousel_image(src = "img/storms.gif"),
    caption = bs_carousel_caption("Exploring 3D and 2D views of tropical storm paths.")
  ) %>%
  bs_append(
    content = bs_carousel_image(src = "img/zikar-colombia.gif"),
    caption = bs_carousel_caption(
      "Comparing overall frequency of Zika virus cases (black) versus frequency within the map (red)."
    )
  ) %>%
  bs_append(
    content = bs_carousel_image(src = "img/bcviz.gif"),
    caption = bs_carousel_caption(
      HTML(
        "Visualizing multiple time series of housing transactions in British Columbia. See <a href='https://vimeo.com/207379729'>here</a> for a full video"
      )
    )
  ) %>%
  # bs_append(
  #   content = bs_carousel_image(src = "img/europe.gif"),
  #   caption = bs_carousel_caption(
  #     "Zooming, hovering, and highlighting on a population map of Europe."
  #   )
  # ) %>%
  # bs_append(
  #   content = bs_carousel_image(src = "img/pedestrians-missing.gif"),
  #   caption = bs_carousel_caption(
  #     "Comparing foot traffic in various train stations among those with highest number of missing values."
  #   )
  # ) %>%
  # TODO: make a better version!
  # bs_append(
  #   content = bs_carousel_image(src = "img/pedestrians-entropy.gif"),
  #   caption = bs_carousel_caption(
  #     "Figure 3b: Comparing foot traffic in train stations with low entropy (red) versus high entropy (blue)."
  #   )
  # ) %>%
  bs_append(
    content = bs_carousel_image(src = "img/quakes.gif"),
    caption = bs_carousel_caption(
      "Exploring relationship between earthquake magnitude and geographic location"
    )
  ) %>%
  bs_append(
    content = bs_carousel_image(src = "img/tour.gif"),
    caption = bs_carousel_caption(
      "Choosing 3 groups of 'similar' US states (via Euclidean distance of arrest data). The rotating graph (aka, a grand tour) cycles through 2D projections of the data -- allowing us to assess how the clustering appears from many different perspectives."
    )
  )


# reusable function for fontawesome icons
icons <- function(names = "terminal") {
  icon_list <- list()
  for (i in seq_along(names)) {
    icon_list[[i]] <- htmltools::tags$i(
      class = sprintf("fa fa-%s fa-fw fa-3x", names[[i]]),
      `aria-hidden` = "true"
    )
    # add a link to the logo if names attr exists
    if (!is.null(names(names))) {
      icon_list[[i]] <- htmltools::tags$a(
        href = names(names)[[i]], target = "_blank", icon_list[[i]]
      )
    }
  }
  htmltools::tags$div(style = "display: inline", icon_list)
}


# flexbox for service content/fontawesome icons
service_box <- div(
  id = "service-box",
  style = "display: flex; flex-wrap: wrap; justify-content: center;",
  div(
    icons(c("line-chart", "bar-chart", "mouse-pointer")),
    h4("Interactive websites that support data analysis tasks")
  ),
  div(
    icons(c("server", "desktop")), 
    h4(a(href = "https://shiny.rstudio.com/", target = "_blank", "Shiny"), " app development, deployment, management, and support")
  ),
  div(
    icons(c("terminal", "user", "graduation-cap")), 
    h4("Programming support and ", a(href = '#training', "training"))
  ),
  div(
    icons(c("question-circle", "info-circle")),
    h4("Statistical consulting")
  ),
  div(
    icons(c("file-code-o", "html5", "file-pdf-o", "file-word-o")),
    h4("Dynamic & reproducible reporting of analytical results")
  ),
  div(
    icons(c("database", "table")),
    h4("Data acquistion, cleaning, management")
  ),
  a(
    href = "https://carsonsievert.typeform.com/to/FGtIgd",
    target = "_blank",
    tags$button(
      type = "button", class = "btn btn-secondary btn-lg",
      htmltools::tags$i(class = "fa fa-paper-plane-o fa-fw fa-2x", `aria-hidden`="true"),
      h4("Request a consultation")
    )
  )
)

# carousel for praise section
carousel_praise <- bs_carousel(id = "carousel-o-praise") %>%
  bs_append(
    content = bs_carousel_image(src = "praise/leigh-alexander.svg")
  ) %>%
  bs_append(
    content = bs_carousel_image(src = "praise/andrew-kosydar.svg")
  ) %>%
  bs_append(
    content = bs_carousel_image(src = "praise/mark-druffel.svg")
  ) %>%
  bs_append(
    content = bs_carousel_image(src = "praise/roy-mendelssohn.svg")
  )

# flexbox of client images
client_images <- div(
  id = "clients",
  style = "display: flex; flex-wrap: wrap; justify-content: center;",
  div(style = "padding: 1em", a(
    href = "https://plot.ly/r/", 
    target = "_blank",
    title = "Plotly",
    img(src = "/img/plotly.png")
  )),
  div(style = "padding: 1em", a(
    href = "http://www.noaa.gov/", 
    target = "_blank",
    title = "NOAA",
    img(src = "/img/noaa.png")
  )),
  div(style = "padding: 1em", a(
    href = "http://www.sandia.gov/", 
    target = "_blank",
    title = "Sandia Labs",
    img(src = "/img/sandia.png")
  )),
  div(style = "padding: 1em", a(
    href = "http://www.oreilly.com/pub/au/7341", 
    target = "_blank",
    title = "O'Reilly Media",
    img(src = "/img/oreilly.png")
  )),
  div(style = "padding: 1em", a(
    href = "https://www.cmu.edu/",
    target = "_blank",
    title = "Carnegie Mellon",
    img(src = "/img/cmu.png")
  )),
  div(style = "padding: 1em", a(
    href = "http://www.uga.edu/", 
    target = "_blank",
    title = "University of Georgia",
    img(src = "/img/uga.png")
  )),
  div(style = "padding: 1em", a(
    href = "http://www.bcstats.gov.bc.ca/", 
    target = "_blank",
    title = "BC Stats (BC Government)",
    img(src = "/img/bcstats.png")
  )),
  div(style = "padding: 1em", a(
    href = "https://www.robustwealth.com/", 
    target = "_blank",
    title = "RobustWealth",
    img(src = "/img/robustwealth.png")
  ))
)


about <- div(
  style = "max-width:700px; margin: auto",
  div(
    id = "about-box",
    style = "display: flex; flex-wrap: wrap; justify-content: center;",
    div(id = "about-pic", a(href = "https://cpsievert.me/", target = "_blank", img(src = "img/carson.png"))),
    div(
      id = "about-txt",
      h3(style = "text-align: left", "Carson Sievert, PhD. Founder and Principal Consultant"),
      h4(includeMarkdown("about.md"))
    )
  )
)

# reusable functions for containerizing content
"%||%" <- function (x, y) if (length(x) > 0) x else y

tagline <- function(title, body = NULL, id = NULL) {
  div(
    id = id %||% title,
    class = "tagline",
    align = "center",
    style = "display: block; max-width: 700px; margin: auto",
    h1(title),
    if (!is.null(body)) h3(body)
  )
}

tagList(
  tagline(
    "Breathing life into data",
    "At Sievert Consulting, we turn data into insight. Our passion is data visualization, but we offer many services surrounding the practice and dissemination of data science."
  ),
  welcome_carousel,
  hr(), br(),
  tagline(
    "Services",
    "We deliver data-driven products & insights faster than the competition thanks to our background in visualization, analytics, and software development."
  ),
  br(),
  div(style = "max-width: 700px; margin: auto", service_box),
  br(), hr(), br(),
  tagline(
    "Clients",
    "Our clients include: startups, government, universities, and corporations"
  ),
  div(
    style = "background-color:#f6f6f6;", 
    div(style = "max-width: 700px; margin: auto", client_images)
  ),
  br(),
  tagline(
    "Training",
    p(a(href = '#about', "Carson"), "is a", a(href = "https://www.rstudio.com/instructors/", "trusted RStudio trainer"),
    "with over 5 years experience teaching university courses and running interactive ", a(href = "https://workshops.cpsievert.me", "workshops"), ". Sign up for his next PLOTCON workshop below,", a(href = "https://carsonsievert.typeform.com/to/FKUSbW", "request an on-site training"),  ", and ", a(href = "https://blog.cpsievert.me/2017/12/04/components-of-a-successful-r-workshop/", "read about"), "his teaching philosophy.")
  ),
  br(),
  div(align = "center", tags$iframe(src = "https://plotcon.plot.ly/r-shiny-dash-r/", height = 600, width = "60%", seamless="seamless", frameBorder="0")),
  br(),
  tagline(
    "Praise",
    "Feedback from clients and workshop attendees"
  ),
  carousel_praise,
  br(),
  tagline("About"),
  about,
  tagline("Contact"),
  div(
    id = "contact-buttons",
    style = "display: flex; flex-wrap: wrap; justify-content: center;",
    div(
      style = "padding: 1em",
      a(
        href = "https://carsonsievert.typeform.com/to/FGtIgd",
        target = "_blank",
        tags$button(
          type = "button", class = "btn btn-secondary btn-lg",
          htmltools::tags$i(class = "fa fa-envelope fa-fw fa-2x", `aria-hidden`="true"),
          h4("Drop us a note")
        )
      )
    ),
    div(
      style = "padding: 1em",
      a(
        href = "https://calendly.com/cpsievert/meeting",
        target = "_blank",
        tags$button(
          type = "button", class = "btn btn-secondary btn-lg",
          htmltools::tags$i(class = "fa fa-calendar fa-fw fa-2x", `aria-hidden`="true"),
          h4("Schedule a meeting")
        )
      )
    )
  ),
  br(), br(), hr()
)
```

<!--
Flip carousel after the initial graphic has had time to play twice
https://stackoverflow.com/questions/14524297/how-to-scroll-to-div-after-click-on-about-or-contact-in-my-menu
-->

```{js}
setTimeout(function() {
  $('#carousel-o-graphics').carousel('next')
}, 27000)

$('ul.nav').find('a').click(function(){
    var href = $(this).attr('href');
    $('html, body').animate({ scrollTop: $(href).offset().top }, 2000);
});
```


```{r footer}
tags$footer(
  div(
    style = "max-width: 700px; height:75px; margin: auto",
    div(
      style = "display:inline-block; margin:auto", 
      a(href = "https://github.com/cpsievert/consulting", target = "_blank", "Copyright 2017 Sievert Consulting")
    ),
    div(
      style = "display:inline-block; float:right; margin:auto",
      icons(c("mailto:cpsievert1@gmail.com" = "envelope-o")),
      icons(c("https://twitter.com/cpsievert" = "twitter")),
      icons(c("https://github.com/cpsievert" = "github")),
      icons(c("https://vimeo.com/cpsievert" = "vimeo"))
    )
  )
)
```
